package apa.impl;

import apa.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultEnergyData <br>
 * @version generated on Mon Mar 09 12:06:31 CDT 2015 by james
 */
public class DefaultEnergyData extends WrappedIndividualImpl implements EnergyData {

    public DefaultEnergyData(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
