package apa.impl;

import apa.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultFacility <br>
 * @version generated on Wed Jan 20 15:20:39 CST 2016 by jovizhu
 */
public class DefaultFacility extends WrappedIndividualImpl implements Facility {

    public DefaultFacility(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#hasCFD
     */
     
    public Collection<? extends CFD> getHasCFD() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASCFD,
                                               DefaultCFD.class);
    }

    public boolean hasHasCFD() {
	   return !getHasCFD().isEmpty();
    }

    public void addHasCFD(CFD newHasCFD) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASCFD,
                                       newHasCFD);
    }

    public void removeHasCFD(CFD oldHasCFD) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASCFD,
                                          oldHasCFD);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#hasEnergyCF
     */
     
    public Collection<? extends EnergyCF> getHasEnergyCF() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASENERGYCF,
                                               DefaultEnergyCF.class);
    }

    public boolean hasHasEnergyCF() {
	   return !getHasEnergyCF().isEmpty();
    }

    public void addHasEnergyCF(EnergyCF newHasEnergyCF) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASENERGYCF,
                                       newHasEnergyCF);
    }

    public void removeHasEnergyCF(EnergyCF oldHasEnergyCF) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASENERGYCF,
                                          oldHasEnergyCF);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#host
     */
     
    public Collection<? extends Service> getHost() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HOST,
                                               DefaultService.class);
    }

    public boolean hasHost() {
	   return !getHost().isEmpty();
    }

    public void addHost(Service newHost) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HOST,
                                       newHost);
    }

    public void removeHost(Service oldHost) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HOST,
                                          oldHost);
    }


}
