package apa.impl;

import apa.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultMService <br>
 * @version generated on Mon Mar 09 12:06:31 CDT 2015 by james
 */
public class DefaultMService extends WrappedIndividualImpl implements MService {

    public DefaultMService(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#hasMicroService
     */
     
    public Collection<? extends MService> getHasMicroService() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASMICROSERVICE,
                                               DefaultMService.class);
    }

    public boolean hasHasMicroService() {
	   return !getHasMicroService().isEmpty();
    }

    public void addHasMicroService(MService newHasMicroService) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASMICROSERVICE,
                                       newHasMicroService);
    }

    public void removeHasMicroService(MService oldHasMicroService) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASMICROSERVICE,
                                          oldHasMicroService);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#hasSCF
     */
     
    public Collection<? extends SCF> getHasSCF() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASSCF,
                                               DefaultSCF.class);
    }

    public boolean hasHasSCF() {
	   return !getHasSCF().isEmpty();
    }

    public void addHasSCF(SCF newHasSCF) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASSCF,
                                       newHasSCF);
    }

    public void removeHasSCF(SCF oldHasSCF) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASSCF,
                                          oldHasSCF);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#hasService
     */
     
    public Collection<? extends Service> getHasService() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASSERVICE,
                                               DefaultService.class);
    }

    public boolean hasHasService() {
	   return !getHasService().isEmpty();
    }

    public void addHasService(Service newHasService) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASSERVICE,
                                       newHasService);
    }

    public void removeHasService(Service oldHasService) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASSERVICE,
                                          oldHasService);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#performAt
     */
     
    public Collection<? extends Facility> getPerformAt() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_PERFORMAT,
                                               DefaultFacility.class);
    }

    public boolean hasPerformAt() {
	   return !getPerformAt().isEmpty();
    }

    public void addPerformAt(Facility newPerformAt) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_PERFORMAT,
                                       newPerformAt);
    }

    public void removePerformAt(Facility oldPerformAt) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_PERFORMAT,
                                          oldPerformAt);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#produces
     */
     
    public Collection<? extends Computer> getProduces() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_PRODUCES,
                                               DefaultComputer.class);
    }

    public boolean hasProduces() {
	   return !getProduces().isEmpty();
    }

    public void addProduces(Computer newProduces) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_PRODUCES,
                                       newProduces);
    }

    public void removeProduces(Computer oldProduces) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_PRODUCES,
                                          oldProduces);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#uses
     */
     
    public Collection<? extends Equipment> getUses() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_USES,
                                               DefaultEquipment.class);
    }

    public boolean hasUses() {
	   return !getUses().isEmpty();
    }

    public void addUses(Equipment newUses) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_USES,
                                       newUses);
    }

    public void removeUses(Equipment oldUses) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_USES,
                                          oldUses);
    }


}
