package apa.impl;

import apa.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultMService <br>
 * @version generated on Wed Jan 20 15:20:39 CST 2016 by jovizhu
 */
public class DefaultMService extends WrappedIndividualImpl implements MService {

    public DefaultMService(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#hasHolisticService
     */
     
    public Collection<? extends Service> getHasHolisticService() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASHOLISTICSERVICE,
                                               DefaultService.class);
    }

    public boolean hasHasHolisticService() {
	   return !getHasHolisticService().isEmpty();
    }

    public void addHasHolisticService(Service newHasHolisticService) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASHOLISTICSERVICE,
                                       newHasHolisticService);
    }

    public void removeHasHolisticService(Service oldHasHolisticService) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASHOLISTICSERVICE,
                                          oldHasHolisticService);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#hasService
     */
     
    public Collection<? extends Service> getHasService() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASSERVICE,
                                               DefaultService.class);
    }

    public boolean hasHasService() {
	   return !getHasService().isEmpty();
    }

    public void addHasService(Service newHasService) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASSERVICE,
                                       newHasService);
    }

    public void removeHasService(Service oldHasService) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASSERVICE,
                                          oldHasService);
    }


}
