package apa.impl;

import apa.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultEquipment <br>
 * @version generated on Wed Jan 20 15:20:39 CST 2016 by jovizhu
 */
public class DefaultEquipment extends WrappedIndividualImpl implements Equipment {

    public DefaultEquipment(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#hasCFD
     */
     
    public Collection<? extends CFD> getHasCFD() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASCFD,
                                               DefaultCFD.class);
    }

    public boolean hasHasCFD() {
	   return !getHasCFD().isEmpty();
    }

    public void addHasCFD(CFD newHasCFD) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASCFD,
                                       newHasCFD);
    }

    public void removeHasCFD(CFD oldHasCFD) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASCFD,
                                          oldHasCFD);
    }


}
