package apa.impl;

import apa.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultEnergySource <br>
 * @version generated on Wed Jan 20 15:20:39 CST 2016 by jovizhu
 */
public class DefaultEnergySource extends WrappedIndividualImpl implements EnergySource {

    public DefaultEnergySource(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
