package apa.impl;

import apa.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultProduct <br>
 * @version generated on Wed Jan 20 15:20:39 CST 2016 by jovizhu
 */
public class DefaultProduct extends WrappedIndividualImpl implements Product {

    public DefaultProduct(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#madeFrom
     */
     
    public Collection<? extends Product> getMadeFrom() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_MADEFROM,
                                               DefaultProduct.class);
    }

    public boolean hasMadeFrom() {
	   return !getMadeFrom().isEmpty();
    }

    public void addMadeFrom(Product newMadeFrom) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_MADEFROM,
                                       newMadeFrom);
    }

    public void removeMadeFrom(Product oldMadeFrom) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_MADEFROM,
                                          oldMadeFrom);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#producedBy
     */
     
    public Collection<? extends MService> getProducedBy() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_PRODUCEDBY,
                                               DefaultMService.class);
    }

    public boolean hasProducedBy() {
	   return !getProducedBy().isEmpty();
    }

    public void addProducedBy(MService newProducedBy) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_PRODUCEDBY,
                                       newProducedBy);
    }

    public void removeProducedBy(MService oldProducedBy) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_PRODUCEDBY,
                                          oldProducedBy);
    }


}
