package apa;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Facility <br>
 * @version generated on Mon Mar 09 12:06:31 CDT 2015 by james
 */

public interface Facility extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#hasCFD
     */
     
    /**
     * Gets all property values for the hasCFD property.<p>
     * 
     * @returns a collection of values for the hasCFD property.
     */
    Collection<? extends CFD> getHasCFD();

    /**
     * Checks if the class has a hasCFD property value.<p>
     * 
     * @return true if there is a hasCFD property value.
     */
    boolean hasHasCFD();

    /**
     * Adds a hasCFD property value.<p>
     * 
     * @param newHasCFD the hasCFD property value to be added
     */
    void addHasCFD(CFD newHasCFD);

    /**
     * Removes a hasCFD property value.<p>
     * 
     * @param oldHasCFD the hasCFD property value to be removed.
     */
    void removeHasCFD(CFD oldHasCFD);


    /* ***************************************************
     * Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#hasEnergyCF
     */
     
    /**
     * Gets all property values for the hasEnergyCF property.<p>
     * 
     * @returns a collection of values for the hasEnergyCF property.
     */
    Collection<? extends EnergyCF> getHasEnergyCF();

    /**
     * Checks if the class has a hasEnergyCF property value.<p>
     * 
     * @return true if there is a hasEnergyCF property value.
     */
    boolean hasHasEnergyCF();

    /**
     * Adds a hasEnergyCF property value.<p>
     * 
     * @param newHasEnergyCF the hasEnergyCF property value to be added
     */
    void addHasEnergyCF(EnergyCF newHasEnergyCF);

    /**
     * Removes a hasEnergyCF property value.<p>
     * 
     * @param oldHasEnergyCF the hasEnergyCF property value to be removed.
     */
    void removeHasEnergyCF(EnergyCF oldHasEnergyCF);


    /* ***************************************************
     * Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#host
     */
     
    /**
     * Gets all property values for the host property.<p>
     * 
     * @returns a collection of values for the host property.
     */
    Collection<? extends Service> getHost();

    /**
     * Checks if the class has a host property value.<p>
     * 
     * @return true if there is a host property value.
     */
    boolean hasHost();

    /**
     * Adds a host property value.<p>
     * 
     * @param newHost the host property value to be added
     */
    void addHost(Service newHost);

    /**
     * Removes a host property value.<p>
     * 
     * @param oldHost the host property value to be removed.
     */
    void removeHost(Service oldHost);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
