package apa;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: MService <br>
 * @version generated on Mon Mar 09 12:06:31 CDT 2015 by james
 */

public interface MService extends Service {

    /* ***************************************************
     * Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#hasMicroService
     */
     
    /**
     * Gets all property values for the hasMicroService property.<p>
     * 
     * @returns a collection of values for the hasMicroService property.
     */
    Collection<? extends MService> getHasMicroService();

    /**
     * Checks if the class has a hasMicroService property value.<p>
     * 
     * @return true if there is a hasMicroService property value.
     */
    boolean hasHasMicroService();

    /**
     * Adds a hasMicroService property value.<p>
     * 
     * @param newHasMicroService the hasMicroService property value to be added
     */
    void addHasMicroService(MService newHasMicroService);

    /**
     * Removes a hasMicroService property value.<p>
     * 
     * @param oldHasMicroService the hasMicroService property value to be removed.
     */
    void removeHasMicroService(MService oldHasMicroService);


    /* ***************************************************
     * Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#hasSCF
     */
     
    /**
     * Gets all property values for the hasSCF property.<p>
     * 
     * @returns a collection of values for the hasSCF property.
     */
    Collection<? extends SCF> getHasSCF();

    /**
     * Checks if the class has a hasSCF property value.<p>
     * 
     * @return true if there is a hasSCF property value.
     */
    boolean hasHasSCF();

    /**
     * Adds a hasSCF property value.<p>
     * 
     * @param newHasSCF the hasSCF property value to be added
     */
    void addHasSCF(SCF newHasSCF);

    /**
     * Removes a hasSCF property value.<p>
     * 
     * @param oldHasSCF the hasSCF property value to be removed.
     */
    void removeHasSCF(SCF oldHasSCF);


    /* ***************************************************
     * Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#hasService
     */
     
    /**
     * Gets all property values for the hasService property.<p>
     * 
     * @returns a collection of values for the hasService property.
     */
    Collection<? extends Service> getHasService();

    /**
     * Checks if the class has a hasService property value.<p>
     * 
     * @return true if there is a hasService property value.
     */
    boolean hasHasService();

    /**
     * Adds a hasService property value.<p>
     * 
     * @param newHasService the hasService property value to be added
     */
    void addHasService(Service newHasService);

    /**
     * Removes a hasService property value.<p>
     * 
     * @param oldHasService the hasService property value to be removed.
     */
    void removeHasService(Service oldHasService);


    /* ***************************************************
     * Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#performAt
     */
     
    /**
     * Gets all property values for the performAt property.<p>
     * 
     * @returns a collection of values for the performAt property.
     */
    Collection<? extends Facility> getPerformAt();

    /**
     * Checks if the class has a performAt property value.<p>
     * 
     * @return true if there is a performAt property value.
     */
    boolean hasPerformAt();

    /**
     * Adds a performAt property value.<p>
     * 
     * @param newPerformAt the performAt property value to be added
     */
    void addPerformAt(Facility newPerformAt);

    /**
     * Removes a performAt property value.<p>
     * 
     * @param oldPerformAt the performAt property value to be removed.
     */
    void removePerformAt(Facility oldPerformAt);


    /* ***************************************************
     * Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#produces
     */
     
    /**
     * Gets all property values for the produces property.<p>
     * 
     * @returns a collection of values for the produces property.
     */
    Collection<? extends Computer> getProduces();

    /**
     * Checks if the class has a produces property value.<p>
     * 
     * @return true if there is a produces property value.
     */
    boolean hasProduces();

    /**
     * Adds a produces property value.<p>
     * 
     * @param newProduces the produces property value to be added
     */
    void addProduces(Computer newProduces);

    /**
     * Removes a produces property value.<p>
     * 
     * @param oldProduces the produces property value to be removed.
     */
    void removeProduces(Computer oldProduces);


    /* ***************************************************
     * Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#uses
     */
     
    /**
     * Gets all property values for the uses property.<p>
     * 
     * @returns a collection of values for the uses property.
     */
    Collection<? extends Equipment> getUses();

    /**
     * Checks if the class has a uses property value.<p>
     * 
     * @return true if there is a uses property value.
     */
    boolean hasUses();

    /**
     * Adds a uses property value.<p>
     * 
     * @param newUses the uses property value to be added
     */
    void addUses(Equipment newUses);

    /**
     * Removes a uses property value.<p>
     * 
     * @param oldUses the uses property value to be removed.
     */
    void removeUses(Equipment oldUses);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
