package apa;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Wed Jan 20 15:20:39 CST 2016 by jovizhu
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#CFD
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CFD.<p>
     * 
     */
    public static final OWLClass CLASS_CFD = factory.getOWLClass(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#CFD"));

    /* ***************************************************
     * Class http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#CPU
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CPU.<p>
     * 
     */
    public static final OWLClass CLASS_CPU = factory.getOWLClass(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#CPU"));

    /* ***************************************************
     * Class http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#Case
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CASE.<p>
     * 
     */
    public static final OWLClass CLASS_CASE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#Case"));

    /* ***************************************************
     * Class http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#Computer
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COMPUTER.<p>
     * 
     */
    public static final OWLClass CLASS_COMPUTER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#Computer"));

    /* ***************************************************
     * Class http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#Equipment
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EQUIPMENT.<p>
     * 
     */
    public static final OWLClass CLASS_EQUIPMENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#Equipment"));

    /* ***************************************************
     * Class http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#Facility
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FACILITY.<p>
     * 
     */
    public static final OWLClass CLASS_FACILITY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#Facility"));

    /* ***************************************************
     * Class http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#Harddrive
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HARDDRIVE.<p>
     * 
     */
    public static final OWLClass CLASS_HARDDRIVE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#Harddrive"));

    /* ***************************************************
     * Class http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#Memory
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MEMORY.<p>
     * 
     */
    public static final OWLClass CLASS_MEMORY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#Memory"));

    /* ***************************************************
     * Class http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#MicroCFD
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MICROCFD.<p>
     * 
     */
    public static final OWLClass CLASS_MICROCFD = factory.getOWLClass(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#MicroCFD"));

    /* ***************************************************
     * Class http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#Motherboard
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MOTHERBOARD.<p>
     * 
     */
    public static final OWLClass CLASS_MOTHERBOARD = factory.getOWLClass(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#Motherboard"));

    /* ***************************************************
     * Class http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#Product
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRODUCT.<p>
     * 
     */
    public static final OWLClass CLASS_PRODUCT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#Product"));

    /* ***************************************************
     * Class http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#SCF
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SCF.<p>
     * 
     */
    public static final OWLClass CLASS_SCF = factory.getOWLClass(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#SCF"));

    /* ***************************************************
     * Class http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#Service
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SERVICE.<p>
     * 
     */
    public static final OWLClass CLASS_SERVICE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#Service"));

    /* ***************************************************
     * Class http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#WCF
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WCF.<p>
     * 
     */
    public static final OWLClass CLASS_WCF = factory.getOWLClass(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#WCF"));

    /* ***************************************************
     * Class http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#energyCF
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ENERGYCF.<p>
     * 
     */
    public static final OWLClass CLASS_ENERGYCF = factory.getOWLClass(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#energyCF"));

    /* ***************************************************
     * Class http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#energyData
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ENERGYDATA.<p>
     * 
     */
    public static final OWLClass CLASS_ENERGYDATA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#energyData"));

    /* ***************************************************
     * Class http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#energySource
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ENERGYSOURCE.<p>
     * 
     */
    public static final OWLClass CLASS_ENERGYSOURCE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#energySource"));

    /* ***************************************************
     * Class http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#mService
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MSERVICE.<p>
     * 
     */
    public static final OWLClass CLASS_MSERVICE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#mService"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#hasCFD
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCFD.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCFD = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#hasCFD"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#hasEnergyCF
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASENERGYCF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASENERGYCF = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#hasEnergyCF"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#hasHolisticService
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASHOLISTICSERVICE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASHOLISTICSERVICE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#hasHolisticService"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#hasMicroCFD
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASMICROCFD.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASMICROCFD = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#hasMicroCFD"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#hasMicroService
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASMICROSERVICE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASMICROSERVICE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#hasMicroService"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#hasSCF
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSCF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSCF = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#hasSCF"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#hasService
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSERVICE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSERVICE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#hasService"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#host
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HOST.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HOST = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#host"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#madeFrom
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property MADEFROM.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MADEFROM = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#madeFrom"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#performAt
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PERFORMAT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PERFORMAT = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#performAt"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#producedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PRODUCEDBY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PRODUCEDBY = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#producedBy"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#produces
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PRODUCES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PRODUCES = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#produces"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#uses
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property USES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_USES = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#uses"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#CFLabel
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CFLABEL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CFLABEL = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#CFLabel"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#name
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property NAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_NAME = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#name"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#quantity
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property QUANTITY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_QUANTITY = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/james/ontologies/2015/0/untitled-ontology-15#quantity"));


}
